#!/bin/bash
# Generated by tools/language_health.py
set -e
cd "$(dirname "$0")"
echo 'Disabling generated\src\WikiAmh.gf (Missing executable: [WinError 2] Le fichier spécifié est introuvable)'
if [ -f 'generated\src\WikiAmh.gf' ]; then mv 'generated\src\WikiAmh.gf' 'generated\src\WikiAmh.gf.SKIP'; fi
echo 'Disabling generated\src\WikiBel.gf (Missing executable: [WinError 2] Le fichier spécifié est introuvable)'
if [ -f 'generated\src\WikiBel.gf' ]; then mv 'generated\src\WikiBel.gf' 'generated\src\WikiBel.gf.SKIP'; fi
echo 'Disabling generated\src\WikiBen.gf (Missing executable: [WinError 2] Le fichier spécifié est introuvable)'
if [ -f 'generated\src\WikiBen.gf' ]; then mv 'generated\src\WikiBen.gf' 'generated\src\WikiBen.gf.SKIP'; fi
echo 'Disabling generated\src\WikiCym.gf (Missing executable: [WinError 2] Le fichier spécifié est introuvable)'
if [ -f 'generated\src\WikiCym.gf' ]; then mv 'generated\src\WikiCym.gf' 'generated\src\WikiCym.gf.SKIP'; fi
echo 'Disabling generated\src\WikiDan.gf (Missing executable: [WinError 2] Le fichier spécifié est introuvable)'
if [ -f 'generated\src\WikiDan.gf' ]; then mv 'generated\src\WikiDan.gf' 'generated\src\WikiDan.gf.SKIP'; fi
echo 'Disabling generated\src\WikiEng.gf (Missing executable: [WinError 2] Le fichier spécifié est introuvable)'
if [ -f 'generated\src\WikiEng.gf' ]; then mv 'generated\src\WikiEng.gf' 'generated\src\WikiEng.gf.SKIP'; fi
echo 'Disabling generated\src\WikiEus.gf (Missing executable: [WinError 2] Le fichier spécifié est introuvable)'
if [ -f 'generated\src\WikiEus.gf' ]; then mv 'generated\src\WikiEus.gf' 'generated\src\WikiEus.gf.SKIP'; fi
echo 'Disabling generated\src\WikiFin.gf (Missing executable: [WinError 2] Le fichier spécifié est introuvable)'
if [ -f 'generated\src\WikiFin.gf' ]; then mv 'generated\src\WikiFin.gf' 'generated\src\WikiFin.gf.SKIP'; fi
echo 'Disabling generated\src\WikiFao.gf (Missing executable: [WinError 2] Le fichier spécifié est introuvable)'
if [ -f 'generated\src\WikiFao.gf' ]; then mv 'generated\src\WikiFao.gf' 'generated\src\WikiFao.gf.SKIP'; fi
echo 'Disabling generated\src\WikiGla.gf (Missing executable: [WinError 2] Le fichier spécifié est introuvable)'
if [ -f 'generated\src\WikiGla.gf' ]; then mv 'generated\src\WikiGla.gf' 'generated\src\WikiGla.gf.SKIP'; fi
