#!/bin/bash
# Generated by tools/language_health
set -e
cd "$(dirname "$0")"
echo 'Disabling gf/WikiEng.gf (File Cat.gf does not exist.)'
if [ -f gf/WikiEng.gf ]; then mv gf/WikiEng.gf gf/WikiEng.gf.SKIP; fi
