#!/bin/bash
# Generated by tools/language_health
set -e
cd "$(dirname "$0")"
echo 'Disabling gf/WikiAmh.gf ([34m)'
if [ -f gf/WikiAmh.gf ]; then mv gf/WikiAmh.gf gf/WikiAmh.gf.SKIP; fi
echo 'Disabling gf/WikiAra.gf (Timeout after 90s)'
if [ -f gf/WikiAra.gf ]; then mv gf/WikiAra.gf gf/WikiAra.gf.SKIP; fi
echo 'Disabling gf/WikiBel.gf (File GrammarBel.gf does not exist.)'
if [ -f gf/WikiBel.gf ]; then mv gf/WikiBel.gf gf/WikiBel.gf.SKIP; fi
echo 'Disabling gf/WikiBul.gf (Timeout after 90s)'
if [ -f gf/WikiBul.gf ]; then mv gf/WikiBul.gf gf/WikiBul.gf.SKIP; fi
echo 'Disabling gf/WikiBen.gf (/mnt/c/MyCode/AbstractWiki/abstract-wiki-architect/generated/src/SyntaxBen.gf:1:0: Syntax error:)'
if [ -f gf/WikiBen.gf ]; then mv gf/WikiBen.gf gf/WikiBen.gf.SKIP; fi
echo 'Disabling gf/WikiCat.gf (Timeout after 90s)'
if [ -f gf/WikiCat.gf ]; then mv gf/WikiCat.gf gf/WikiCat.gf.SKIP; fi
echo 'Disabling gf/WikiCze.gf (File GrammarCze.gf does not exist.)'
if [ -f gf/WikiCze.gf ]; then mv gf/WikiCze.gf gf/WikiCze.gf.SKIP; fi
echo 'Disabling gf/WikiCym.gf (/mnt/c/MyCode/AbstractWiki/abstract-wiki-architect/generated/src/SyntaxCym.gf:1:0: Syntax error:)'
if [ -f gf/WikiCym.gf ]; then mv gf/WikiCym.gf gf/WikiCym.gf.SKIP; fi
echo 'Disabling gf/WikiGre.gf (Timeout after 90s)'
if [ -f gf/WikiGre.gf ]; then mv gf/WikiGre.gf gf/WikiGre.gf.SKIP; fi
echo 'Disabling gf/WikiEst.gf (Timeout after 90s)'
if [ -f gf/WikiEst.gf ]; then mv gf/WikiEst.gf gf/WikiEst.gf.SKIP; fi
echo 'Disabling gf/WikiEus.gf (Timeout after 90s)'
if [ -f gf/WikiEus.gf ]; then mv gf/WikiEus.gf gf/WikiEus.gf.SKIP; fi
echo 'Disabling gf/WikiFin.gf (Timeout after 90s)'
if [ -f gf/WikiFin.gf ]; then mv gf/WikiFin.gf gf/WikiFin.gf.SKIP; fi
echo 'Disabling gf/WikiFao.gf (File GrammarFao.gf does not exist.)'
if [ -f gf/WikiFao.gf ]; then mv gf/WikiFao.gf gf/WikiFao.gf.SKIP; fi
echo 'Disabling gf/WikiGla.gf (File GrammarGla.gf does not exist.)'
if [ -f gf/WikiGla.gf ]; then mv gf/WikiGla.gf gf/WikiGla.gf.SKIP; fi
echo 'Disabling gf/WikiHeb.gf ([34m)'
if [ -f gf/WikiHeb.gf ]; then mv gf/WikiHeb.gf gf/WikiHeb.gf.SKIP; fi
echo 'Disabling gf/WikiHrv.gf (File GrammarHrv.gf does not exist.)'
if [ -f gf/WikiHrv.gf ]; then mv gf/WikiHrv.gf gf/WikiHrv.gf.SKIP; fi
echo 'Disabling gf/WikiHun.gf ([34m)'
if [ -f gf/WikiHun.gf ]; then mv gf/WikiHun.gf gf/WikiHun.gf.SKIP; fi
echo 'Disabling gf/WikiHye.gf (File GrammarHye.gf does not exist.)'
if [ -f gf/WikiHye.gf ]; then mv gf/WikiHye.gf gf/WikiHye.gf.SKIP; fi
echo 'Disabling gf/WikiInd.gf (/mnt/c/MyCode/AbstractWiki/abstract-wiki-architect/generated/src/SyntaxInd.gf:1:0: Syntax error:)'
if [ -f gf/WikiInd.gf ]; then mv gf/WikiInd.gf gf/WikiInd.gf.SKIP; fi
echo 'Disabling gf/WikiInu.gf (/mnt/c/MyCode/AbstractWiki/abstract-wiki-architect/generated/src/SyntaxInu.gf:1:0: Syntax error:)'
if [ -f gf/WikiInu.gf ]; then mv gf/WikiInu.gf gf/WikiInu.gf.SKIP; fi
echo 'Disabling gf/WikiKaz.gf (File GrammarKaz.gf does not exist.)'
if [ -f gf/WikiKaz.gf ]; then mv gf/WikiKaz.gf gf/WikiKaz.gf.SKIP; fi
echo 'Disabling gf/WikiKor.gf (File SyntaxKor.gf does not exist.)'
if [ -f gf/WikiKor.gf ]; then mv gf/WikiKor.gf gf/WikiKor.gf.SKIP; fi
echo 'Disabling gf/WikiLit.gf (File SyntaxLit.gf does not exist.)'
if [ -f gf/WikiLit.gf ]; then mv gf/WikiLit.gf gf/WikiLit.gf.SKIP; fi
echo 'Disabling gf/WikiLav.gf (Timeout after 90s)'
if [ -f gf/WikiLav.gf ]; then mv gf/WikiLav.gf gf/WikiLav.gf.SKIP; fi
echo 'Disabling gf/WikiMkd.gf (File GrammarMkd.gf does not exist.)'
if [ -f gf/WikiMkd.gf ]; then mv gf/WikiMkd.gf gf/WikiMkd.gf.SKIP; fi
echo 'Disabling gf/WikiMal.gf (/mnt/c/MyCode/AbstractWiki/abstract-wiki-architect/generated/src/SyntaxMal.gf:1:0: Syntax error:)'
if [ -f gf/WikiMal.gf ]; then mv gf/WikiMal.gf gf/WikiMal.gf.SKIP; fi
echo 'Disabling gf/WikiMay.gf (File GrammarMay.gf does not exist.)'
if [ -f gf/WikiMay.gf ]; then mv gf/WikiMay.gf gf/WikiMay.gf.SKIP; fi
echo 'Disabling gf/WikiMlt.gf (Timeout after 90s)'
if [ -f gf/WikiMlt.gf ]; then mv gf/WikiMlt.gf gf/WikiMlt.gf.SKIP; fi
echo 'Disabling gf/WikiPor.gf (Timeout after 90s)'
if [ -f gf/WikiPor.gf ]; then mv gf/WikiPor.gf gf/WikiPor.gf.SKIP; fi
echo 'Disabling gf/WikiRon.gf (Timeout after 90s)'
if [ -f gf/WikiRon.gf ]; then mv gf/WikiRon.gf gf/WikiRon.gf.SKIP; fi
echo 'Disabling gf/WikiSlo.gf (File GrammarSlo.gf does not exist.)'
if [ -f gf/WikiSlo.gf ]; then mv gf/WikiSlo.gf gf/WikiSlo.gf.SKIP; fi
echo 'Disabling gf/WikiSlv.gf ([34m)'
if [ -f gf/WikiSlv.gf ]; then mv gf/WikiSlv.gf gf/WikiSlv.gf.SKIP; fi
echo 'Disabling gf/WikiSqi.gf (File GrammarSqi.gf does not exist.)'
if [ -f gf/WikiSqi.gf ]; then mv gf/WikiSqi.gf gf/WikiSqi.gf.SKIP; fi
echo 'Disabling gf/WikiSwa.gf ([34m)'
if [ -f gf/WikiSwa.gf ]; then mv gf/WikiSwa.gf gf/WikiSwa.gf.SKIP; fi
echo 'Disabling gf/WikiTam.gf (File GrammarTam.gf does not exist.)'
if [ -f gf/WikiTam.gf ]; then mv gf/WikiTam.gf gf/WikiTam.gf.SKIP; fi
echo 'Disabling gf/WikiTel.gf ([34m)'
if [ -f gf/WikiTel.gf ]; then mv gf/WikiTel.gf gf/WikiTel.gf.SKIP; fi
echo 'Disabling gf/WikiTgl.gf (/mnt/c/MyCode/AbstractWiki/abstract-wiki-architect/generated/src/SyntaxTgl.gf:1:0: Syntax error:)'
if [ -f gf/WikiTgl.gf ]; then mv gf/WikiTgl.gf gf/WikiTgl.gf.SKIP; fi
echo 'Disabling gf/WikiTur.gf ([34m)'
if [ -f gf/WikiTur.gf ]; then mv gf/WikiTur.gf gf/WikiTur.gf.SKIP; fi
echo 'Disabling gf/WikiUkr.gf (File GrammarUkr.gf does not exist.)'
if [ -f gf/WikiUkr.gf ]; then mv gf/WikiUkr.gf gf/WikiUkr.gf.SKIP; fi
echo 'Disabling gf/WikiVie.gf (/mnt/c/MyCode/AbstractWiki/abstract-wiki-architect/generated/src/SyntaxVie.gf:1:0: Syntax error:)'
if [ -f gf/WikiVie.gf ]; then mv gf/WikiVie.gf gf/WikiVie.gf.SKIP; fi
echo 'Disabling gf/WikiZul.gf (File GrammarZul.gf does not exist.)'
if [ -f gf/WikiZul.gf ]; then mv gf/WikiZul.gf gf/WikiZul.gf.SKIP; fi
