# gf/build_300.py
# =========================================================================
# GF BUILD SCRIPT FOR MASSIVE MULTILINGUAL SUPPORT (~300 Languages)
#
# This script manages the compilation process:
# 1. Defines the list of RGL languages (ISO 639-3 codes).
# 2. Generates the language-specific instance files that bridge AbstractWiki.gf
#    and the RGL Dictionary for each language.
# 3. Executes the 'gf' command-line compiler to produce the final Wiki.pgf.
# =========================================================================

import os
import subprocess
import sys

# --- CONFIGURATION ---

# 1. The full list of RGL-supported languages (ISO 639-3 codes).
# NOTE: This list must be exhaustive to cover all 300 languages. 
# The list below is an abbreviated example; replace with the complete list.
RGL_LANGUAGES = [
    "eng", "fra", "deu", "spa", "ita", "swe", "por", "rus", "zho", "jpn",
    "ara", "hin", "fin", "est", "swa", "tur", "bul", "pol", 
    # ... add all other ISO 639-3 codes supported by RGL here ...
]

# File paths
GF_DIR = os.path.dirname(os.path.abspath(__file__))
PGF_OUTPUT_FILE = os.path.join(GF_DIR, "Wiki.pgf")
ABSTRACT_WIKI = "AbstractWiki"
VOCABULARY = "Vocabulary"
MASTER_GF_FILE = os.path.join(GF_DIR, f"{ABSTRACT_WIKI}.gf")

# --- CORE LOGIC ---

def generate_language_files(lang_code: str) -> str:
    """
    Generates a temporary GF file that specifies the concrete realization
    for a single language. This file uses the functor definitions in WikiI.gf
    and VocabularyI.gf.

    Returns the content of the generated GF file.
    """
    # RGL Dictionary names are typically Dict<LangCode> (e.g., DictEng)
    dict_name = f"Dict{lang_code.capitalize()}"
    
    # 1. Import all required RGL modules for the specific language.
    # 2. Instantiate the WikiI functor using the RGL Concrete Syntax (Syntax<LangCode>).
    # 3. Instantiate the VocabularyI functor using the RGL Dictionary (Dict<LangCode>).
    #
    # This single file combines the logic for structure (WikiI) and words (VocabularyI)
    # for one language, preparing it for compilation.

    content = f"""
-- Automatically generated by gf/build_300.py
-- Language: {lang_code}

-- 1. Import RGL Modules (Syntax and Dictionary for the specific language)
import RGL.{dict_name} as D ;
import RGL.Syntax{lang_code.capitalize()} ;

-- 2. Instantiate the WikiI Functor (Structural Rules)
instance Wiki{lang_code.capitalize()} of AbstractWiki = open RGL.Syntax{lang_code.capitalize()} in 
  WikiI ** open RGL.Syntax{lang_code.capitalize()} in {{}} ;

-- 3. Instantiate the VocabularyI Functor (Lexical Rules)
instance Vocabulary{lang_code.capitalize()} of Vocabulary = 
  VocabularyI ** open D in {{}} ;

"""
    return content

def create_master_gf_file(concrete_files: list[str]):
    """
    Creates a temporary master GF file (e.g., AbstractWiki_master.gf) 
    that imports all individual language instances, ensuring they are all 
    compiled into the final PGF file.
    """
    master_imports = "\n".join([f"import {f.replace('.gf', '')};" for f in concrete_files])

    content = f"""
-- ====================================================================
-- MASTER COMPILATION FILE (Generated)
-- ====================================================================
-- Imports all necessary GF modules for compilation.

-- Core Abstract/Functors
import AbstractWiki ;
import Vocabulary ;
import WikiI ;
import VocabularyI ;

-- Import all generated Concrete Syntax files
{master_imports}
"""
    master_path = os.path.join(GF_DIR, f"{ABSTRACT_WIKI}_master.gf")
    with open(master_path, 'w') as f:
        f.write(content)
    return master_path

def compile_gf(master_file: str):
    """
    Executes the GF compiler command.
    """
    print(f"--- Compiling all {len(RGL_LANGUAGES)} languages into {PGF_OUTPUT_FILE} ---")
    
    # Standard GF compilation command: 'gf -pgf <MasterFile.gf>'
    command = ["gf", "-pgf", master_file]
    
    try:
        # Run the compilation command, capturing output for debugging
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            check=True, # Raise error if compilation fails
            cwd=GF_DIR # Execute in the 'gf' directory
        )
        print("GF Compilation successful.")
        # The GF compiler outputs the PGF file next to the master file by default.
        # Rename it to the final expected name: Wiki.pgf
        os.rename(os.path.join(GF_DIR, master_file.replace(".gf", ".pgf")), PGF_OUTPUT_FILE)
        print(f"Final PGF written to: {PGF_OUTPUT_FILE}")
        # Cleanup temporary files
        os.remove(master_file)
        
    except subprocess.CalledProcessError as e:
        print("ERROR: GF Compilation failed!")
        print(f"Standard Output:\n{e.stdout}")
        print(f"Standard Error:\n{e.stderr}")
        sys.exit(1)
    except FileNotFoundError:
        print("ERROR: GF compiler not found. Ensure 'gf' is installed and in your PATH.")
        sys.exit(1)


def main():
    """Main execution function."""
    print("GF Multilingual Build Script Starting...")
    
    generated_gf_files = []
    
    # 1. Generate all language-specific files (e.g., WikiEng.gf, WikiFra.gf)
    for lang_code in RGL_LANGUAGES:
        file_name = f"Wiki{lang_code.capitalize()}.gf"
        file_path = os.path.join(GF_DIR, file_name)
        
        try:
            content = generate_language_files(lang_code)
            with open(file_path, 'w') as f:
                f.write(content)
            generated_gf_files.append(file_name)
            # print(f"  Generated {file_name}")
        except Exception as e:
            print(f"Warning: Could not generate file for {lang_code}. Skipping. Error: {e}")
            
    print(f"Successfully generated {len(generated_gf_files)} language bridge files.")
    
    # 2. Create the master compilation file
    master_file = create_master_gf_file(generated_gf_files)
    print(f"Created master file: {master_file}")
    
    # 3. Compile the grammar
    compile_gf(master_file)
    
    # 4. Cleanup individual temporary language files
    for file_name in generated_gf_files:
        os.remove(os.path.join(GF_DIR, file_name))
    
    print("Build script finished. All temporary files cleaned up.")


if __name__ == "__main__":
    # Ensure the script is run from the correct directory if needed, 
    # but the use of os.path.join and GF_DIR should handle execution from anywhere.
    main()