import json
import csv
import os
import sys

# Add project root to path so we can find 'data' and 'qa_tools'
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from prototypes.shared_romance_engine import render_romance_bio

def load_config():
    path = os.path.join('data', 'romance_grammar_matrix.json')
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def run_tests():
    print("🚀 STARTING LOCAL TEST RUNNER...")
    print("--------------------------------")
    
    config = load_config()
    matrix = config['languages']
    
    # Path to the CSVs generated by your Test Factory
    test_dir = os.path.join('qa_tools', 'generated_datasets')
    
    if not os.path.exists(test_dir):
        print(f"❌ Error: Test directory '{test_dir}' not found. Run 'test_suite_generator.py' first.")
        return

    files = [f for f in os.listdir(test_dir) if f.endswith('.csv')]
    
    if not files:
        print("⚠️  No CSV files found. Please generate tests first.")
        return

    total_passed = 0
    total_failed = 0
    total_skipped = 0

    for filename in files:
        # Extract language code from filename (test_suite_it.csv -> it)
        lang_code = filename.split('_')[-1].replace('.csv', '')
        
        if lang_code not in matrix:
            print(f"⚠️  Skipping {filename}: Language '{lang_code}' not in Grammar Matrix.")
            continue
            
        print(f"\n📂 Testing Language: {matrix[lang_code]['name']} ({lang_code})")
        
        filepath = os.path.join(test_dir, filename)
        
        with open(filepath, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            
            for row in reader:
                # Check if we have an expected output to compare against
                expected = row.get('EXPECTED_FULL_SENTENCE', '').strip()
                
                # Inputs
                name = row['Name']
                gender = row['Gender (Male/Female)']
                
                # Handling the placeholder brackets [Actor] -> Actor
                prof = row[f'Profession_Lemma_in_{matrix[lang_code]["name"]}'].replace('[', '').replace(']', '')
                nat = row[f'Nationality_Lemma_in_{matrix[lang_code]["name"]}'].replace('[', '').replace(']', '')
                
                # Skip if the CSV hasn't been filled out by AI yet
                if not prof or prof.startswith('Concept'):
                    total_skipped += 1
                    continue

                # --- THE MOMENT OF TRUTH ---
                # We call the Shared Engine with the specific config chunk
                actual = render_romance_bio(name, gender, prof, nat, matrix[lang_code])
                
                if expected:
                    if actual == expected:
                        print(f"  ✅ PASS: {actual}")
                        total_passed += 1
                    else:
                        print(f"  ❌ FAIL: {name}")
                        print(f"     Expected: {expected}")
                        print(f"     Got:      {actual}")
                        total_failed += 1
                else:
                    # If no expected output, just print result for manual checking
                    print(f"  👀 PREVIEW: {actual}")
                    total_skipped += 1

    print("\n--------------------------------")
    print(f"SUMMARY: {total_passed} Passed | {total_failed} Failed | {total_skipped} Pending/Skipped")
    
    if total_failed == 0 and total_passed > 0:
        print("🎉 GREAT SUCCESS! The engine is consistent with the test data.")

if __name__ == "__main__":
    # Ensure we run from project root context
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    os.chdir(project_root)
    
    run_tests()