# tools/everything_matrix/qa_scanner.py
import os
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict

try:
    import pgf
except ImportError:
    pgf = None

def scan_artifacts(lang: str, gf_dir: Path) -> Dict[str, float]:
    """
    Scans Zone D (Quality) artifacts.
    Returns:
      BIN: 1.0 if language is present in AbstractWiki.pgf, else 0.0.
      TEST: 0.0 - 1.0 representing the pass rate in the latest regression test.
    """
    stats = {
        "BIN": 0.0,
        "TEST": 0.0
    }

    # 1. Scan Binary (BIN)
    # We check if the language code exists inside the compiled PGF.
    pgf_path = gf_dir / "AbstractWiki.pgf"
    if pgf and pgf_path.exists():
        try:
            grammar = pgf.readPGF(str(pgf_path))
            # GF languages are usually capitalized, e.g., "WikiFra"
            target_lang = f"Wiki{lang.capitalize()}"
            if target_lang in grammar.languages:
                stats["BIN"] = 1.0
        except Exception as e:
            print(f"⚠️  [QA Scanner] PGF Read Error: {e}")
            # If PGF is corrupt, BIN stays 0.0

    # 2. Scan Test Results (TEST)
    # We look for a JUnit XML report generated by pytest
    # Expected path: data/tests/reports/junit.xml
    # (Configured in pytest.ini: --junitxml=data/tests/reports/junit.xml)
    report_path = gf_dir.parent / "data" / "tests" / "reports" / "junit.xml"
    
    if report_path.exists():
        stats["TEST"] = _parse_junit_report(lang, report_path)
    else:
        # If no report exists, check if we have a simple log file fallback
        # or just return 0.0 (Untested)
        pass

    return stats

def _parse_junit_report(lang: str, path: Path) -> float:
    """
    Parses a JUnit XML file to calculate pass rate for a specific language.
    Assumes test case names contain the language code (e.g., 'test_bio_fra').
    """
    try:
        tree = ET.parse(path)
        root = tree.getroot()
        
        total_tests = 0
        passed_tests = 0
        
        # Iterate over all test cases
        for testcase in root.iter("testcase"):
            name = testcase.get("name", "").lower()
            
            # Filter tests relevant to this language
            # Logic: Look for "_fra" suffix or argument in the test name
            if f"_{lang}" in name or f"[{lang}]" in name:
                total_tests += 1
                
                # Check for failure/error elements
                failures = testcase.find("failure")
                errors = testcase.find("error")
                
                if failures is None and errors is None:
                    passed_tests += 1
        
        if total_tests == 0:
            return 0.0
            
        return round(passed_tests / total_tests, 2)

    except ET.ParseError:
        print(f"⚠️  [QA Scanner] Malformed JUnit XML at {path}")
        return 0.0
    except Exception as e:
        print(f"⚠️  [QA Scanner] Error parsing tests: {e}")
        return 0.0