// architect_frontend/src/types/EverythingMatrix.ts

/**
 * The Root Object for the Everything Matrix v2.1
 * Matches data/indices/everything_matrix.json generated by build_index.py
 */
export interface EverythingMatrix {
  timestamp: number; // Unix timestamp (float/int from Python time.time())
  stats: {
    total_languages: number;
    production_ready: number; // maturity >= 8
    safe_mode: number;        // strategy = SAFE_MODE
    skipped: number;          // strategy = SKIP
  };
  languages: Record<string, LanguageEntry>;
}

/**
 * Represents a single Language in the Matrix
 */
export interface LanguageEntry {
  meta: LanguageMeta;
  zones: LanguageZones;
  verdict: LanguageVerdict;
}

/**
 * Metadata about the language identity
 */
export interface LanguageMeta {
  iso: string;     // e.g. "eng", "fra"
  tier: number;    // 1 (RGL) or 3 (Factory)
  origin: string;  // "rgl" or "factory"
  folder: string;  // e.g. "english" or "generated"
  name?: string;   // Optional display name (if added by backend later)
}

/**
 * The 4 Health Zones containing the 14 Metrics
 */
export interface LanguageZones {
  A_RGL: ZoneA_RGL;
  B_LEX: ZoneB_Lexicon;
  C_APP: ZoneC_App;
  D_QA:  ZoneD_Quality;
}

// --- ZONE DEFINITIONS (All scores 0.0 - 10.0) ---

/**
 * Zone A: Logic & Grammar Engine (RGL)
 */
export interface ZoneA_RGL {
  CAT: number;  // Categories (CatX.gf)
  NOUN: number; // Morphology (NounX.gf)
  PARA: number; // Paradigms (ParadigmsX.gf)
  GRAM: number; // Grammar Core (GrammarX.gf)
  SYN: number;  // Syntax API (SyntaxX)
}

/**
 * Zone B: Data & Lexicon
 */
export interface ZoneB_Lexicon {
  SEED: number; // Core Vocabulary (core.json)
  CONC: number; // Domain Concepts (people.json)
  WIDE: number; // Bulk Imports (wide.csv)
  SEM: number;  // Semantic Alignment (Wikidata QIDs)
}

/**
 * Zone C: Application & Use Case
 */
export interface ZoneC_App {
  PROF: number; // Bio-Ready (Professions/Nationalities)
  ASST: number; // Chat-Ready (Dialog)
  ROUT: number; // Topology Routing Configured
}

/**
 * Zone D: Quality Assurance
 */
export interface ZoneD_Quality {
  BIN: number;  // Present in compiled .pgf binary
  TEST: number; // Regression Test Pass Rate
}

/**
 * High-level status and Orchestrator decision
 */
export interface LanguageVerdict {
  maturity_score: number;      // Weighted Average (0.0 - 10.0)
  build_strategy: 'HIGH_ROAD' | 'SAFE_MODE' | 'SKIP' | string;
  runnable: boolean;           // If false, excluded from Runtime to prevent crash
}